FROM nginx:1.15.8

WORKDIR /developers-portal
COPY . /developers-portal

RUN cp /developers-portal/deploy/docs/nginx.conf /etc/nginx/nginx.conf

CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf" && nginx -g 'daemon off;'
